### ISSUE TITLE
Will this be updated for Foundryvtt 11?

### ISSUE THREAD

**Issue by agentKnipe** [aolkin/cyberpunkred-importer#1]
Will this be updated for FoundryVTT 11?

**Comment by aolkin** [comment]
I haven't gotten around to updating my Foundry installations to v11 myself quite yet so I can't commit to an ECD, but I would like to update this in the near future provided Foundry V11 and CPR system changes don't make that unfeasible.

**Comment by Zenyeeta** [comment]
I would love an update for  FoundryVTT 11.  Im trying to run a game for some new players and this importer would be super helpful with facilitating that!

**Comment by aolkin** [comment]
Apologies for the radio silence. Finally got around to updating my server recently, hoping to take care of this this week.

I have not yet looked into the data model and system changes yet though, so I have no idea how much effort it will be.

**Comment by aolkin** [comment]
I did not encounter any issues while running this on Foundry v11, but did have to make minor updates to support the CPR System v0.88.2, now available in [v0.3.0](https://github.com/aolkin/cyberpunkred-importer/releases/tag/v0.3.0) also [live in the Foundry package database](https://foundryvtt.com/packages/cyberpunkred-importer).
