### ISSUE TITLE
Cyberware Import Error (Grafted Muscle and Bone Lace)

### ISSUE THREAD

**Issue by Carciphona23** [aolkin/cyberpunkred-importer#3]
So far players aren't having al of their cyberware imported over from the transfer despite meeting all prerequisite and NPCs simply can't be imported over at all, unless that wasn't part of the module.

**Comment by Carciphona23** [comment]
Here's an id import code for an NPC Harden netrunner (1S7YVU) and Player character (YGELH7)

**Comment by Xhasher** [comment]
I have the same problem importing NPC. There's any chance you're going to support that? Thanks in advance for your work!

**Comment by aolkin** [comment]
For `YGELH7`, it looks like that character had Grafted Muscle and Bone Lace, which was not recognized correctly. I did not encounter any other errors trying to import that character. I will track that bugfix with this issue.

I have opened a separate issue to track NPC support in case it is more complex and takes longer to implement: #4
